// <auto-generated />
namespace BootcampManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_new_model_department : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_new_model_department));
        
        string IMigrationMetadata.Id
        {
            get { return "201904100927154_add_new_model_department"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
