// <auto-generated />
namespace BootcampManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class almost_all_migration_and_fixed_region_district : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(almost_all_migration_and_fixed_region_district));
        
        string IMigrationMetadata.Id
        {
            get { return "201904110247582_almost_all_migration_and_fixed_region_district"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
